### PR TITLE
Change to make compatible with Nim release where 'nil' doesn't exist …

### PR DESCRIPTION
**Pull request by kingoodie**
…for string and seq

Tests are green now with nim devel compiled today.

### CODE REVIEW

**Comment by dom96** [comment]
Doesn't this add ambiguity?

For example: key doesn't exist vs key is an empty list?

**Comment by euantorano** [comment]
I wonder if it would make sense for `get()` to return an `Option[T]` instead, with `None` indicating a non-existent key, and `Some("")` or `Some(@[])` being an empty string/list?

**Comment by dom96** [comment]
Yes, that is what I had in mind. But this would break everything :(

**Comment by Araq** [comment]
``version       = "0.2.0"``, 30 stars, 11 forks. I wouldn't worry and create an API that makes sense.

**Comment by dom96** [comment]
Closing in favour of #16.

**Pull request closed without merging**
